# Generated by Django 5.2.7 on 2026-03-22 09:54

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('classID', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('className', models.CharField(blank=True, max_length=100, null=True)),
                ('year', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='EnrollSubject',
            fields=[
                ('enrollSubjectID', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('subjectID', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('subjectCode', models.CharField(blank=True, max_length=20, null=True)),
                ('subjectName', models.CharField(max_length=150)),
                ('year', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('studentID', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('classID', models.ForeignKey(blank=True, db_column='classID', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='sashcapp.class')),
                ('enrollSubjectID', models.ForeignKey(blank=True, db_column='enrollSubjectID', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='sashcapp.enrollsubject')),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('teacherID', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_principal', models.BooleanField(default=False)),
                ('enrollSubjectID', models.ForeignKey(blank=True, db_column='enrollSubjectID', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teachers', to='sashcapp.enrollsubject')),
            ],
        ),
        migrations.AddField(
            model_name='class',
            name='teacherID',
            field=models.ForeignKey(blank=True, db_column='teacherID', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_classes', to='sashcapp.teacher'),
        ),
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('adminID', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('teacherID', models.ForeignKey(blank=True, db_column='teacherID', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admins', to='sashcapp.teacher')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('userID', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254)),
                ('name', models.CharField(max_length=150)),
                ('role', models.JSONField(blank=True, db_column='role', default=list)),
                ('gender', models.CharField(blank=True, max_length=20, null=True)),
                ('profilePicture', models.TextField(blank=True, null=True)),
                ('year', models.IntegerField(blank=True, null=True)),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
                ('adminID', models.OneToOneField(blank=True, db_column='adminID', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_profile', to='sashcapp.admin')),
                ('studentID', models.OneToOneField(blank=True, db_column='studentID', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_profile', to='sashcapp.student')),
                ('teacherID', models.OneToOneField(blank=True, db_column='teacherID', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_profile', to='sashcapp.teacher')),
            ],
        ),
        migrations.CreateModel(
            name='PasswordResetToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('is_used', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='password_reset_tokens', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['token'], name='sashcapp_pa_token_31c8b2_idx'), models.Index(fields=['user', '-created_at'], name='sashcapp_pa_user_id_f6f06a_idx')],
            },
        ),
        migrations.CreateModel(
            name='Headcount',
            fields=[
                ('headcountID', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('TOVmark', models.FloatField(blank=True, null=True)),
                ('TOVgrade', models.CharField(blank=True, max_length=5, null=True)),
                ('ETRmark', models.FloatField(blank=True, null=True)),
                ('ETRgrade', models.CharField(blank=True, max_length=5, null=True)),
                ('AR1mark', models.FloatField(blank=True, null=True)),
                ('AR1grade', models.CharField(blank=True, max_length=5, null=True)),
                ('AR2mark', models.FloatField(blank=True, null=True)),
                ('AR2grade', models.CharField(blank=True, max_length=5, null=True)),
                ('OTI1mark', models.FloatField(blank=True, null=True)),
                ('OTI1grade', models.CharField(blank=True, max_length=5, null=True)),
                ('OTI2mark', models.FloatField(blank=True, null=True)),
                ('OTI2grade', models.CharField(blank=True, max_length=5, null=True)),
                ('userID', models.ForeignKey(db_column='userID', on_delete=django.db.models.deletion.CASCADE, related_name='headcounts', to=settings.AUTH_USER_MODEL)),
                ('subjectID', models.ForeignKey(db_column='subjectID', on_delete=django.db.models.deletion.CASCADE, related_name='headcounts', to='sashcapp.subject')),
            ],
            options={
                'unique_together': {('userID', 'subjectID')},
            },
        ),
        migrations.CreateModel(
            name='SubjectEnrollment',
            fields=[
                ('subjectEnrollmentID', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('classID', models.ForeignKey(blank=True, db_column='classID', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subject_enrollments', to='sashcapp.class')),
                ('enrollSubjectID', models.ForeignKey(db_column='enrollSubjectID', on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='sashcapp.enrollsubject')),
                ('subjectID', models.ForeignKey(db_column='subjectID', on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='sashcapp.subject')),
            ],
            options={
                'unique_together': {('enrollSubjectID', 'subjectID', 'classID')},
            },
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.UniqueConstraint(condition=models.Q(('year__isnull', False)), fields=('email', 'year'), name='unique_email_per_year'),
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.UniqueConstraint(condition=models.Q(('year__isnull', True)), fields=('email',), name='unique_email_no_year'),
        ),
    ]
