# Generated by Django 5.2.7 on 2026-03-22 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sashcapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordresettoken',
            name='token',
            field=models.CharField(db_index=True, max_length=64, unique=True),
        ),
        migrations.AddConstraint(
            model_name='class',
            constraint=models.UniqueConstraint(condition=models.Q(('year__isnull', False)), fields=('className', 'year'), name='unique_class_name_per_year'),
        ),
        migrations.AddConstraint(
            model_name='subject',
            constraint=models.UniqueConstraint(condition=models.Q(('year__isnull', False)), fields=('subjectName', 'year'), name='unique_subject_name_per_year'),
        ),
    ]
