# Generated by Django 5.2.7 on 2026-03-27 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('sashcapp', '0002_alter_passwordresettoken_token_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='class',
            index=models.Index(fields=['year'], name='class_year_idx'),
        ),
        migrations.AddIndex(
            model_name='headcount',
            index=models.Index(fields=['userID', 'subjectID'], name='headcount_user_subject_idx'),
        ),
        migrations.AddIndex(
            model_name='headcount',
            index=models.Index(fields=['subjectID'], name='headcount_subject_idx'),
        ),
        migrations.AddIndex(
            model_name='subject',
            index=models.Index(fields=['year'], name='subject_year_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['year'], name='user_year_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['email', 'year'], name='user_email_year_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['studentID'], name='user_student_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['teacherID'], name='user_teacher_idx'),
        ),
    ]
