# Generated by Django 5.2.7 on 2026-04-09 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sashcapp', '0004_feedback'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feedback',
            old_name='message',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='feedback',
            old_name='subject',
            new_name='title',
        ),
    ]
