# Generated by Django 5.2.7 on 2026-04-19 20:18

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sashcapp', '0005_rename_message_feedback_description_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='passwordresettoken',
            name='sashcapp_pa_user_id_f6f06a_idx',
        ),
        migrations.RemoveField(
            model_name='passwordresettoken',
            name='id',
        ),
        migrations.AddField(
            model_name='passwordresettoken',
            name='tokenID',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AddIndex(
            model_name='passwordresettoken',
            index=models.Index(fields=['user_id', '-created_at'], name='sashcapp_pa_user_id_f6f06a_idx'),
        ),
    ]
